In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
%load_ext autoreload
%autoreload 2

import rbm_qst
import rbm_classic

import utils
import utils_phases
import paper_functions

In [3]:
quantum_system = [(0,0,1),
                  (0,1,0),
                  (1,0,0)]
amplitudes = [1/np.sqrt(3)] * 3
phases = [0] * 3

operations = "III"
res = utils_phases.system_evolution(quantum_system, operations, amplitudes, phases)

In [4]:
res

{(0, 0, 1): (0.5773502691896258+0j),
 (0, 1, 0): (0.5773502691896258+0j),
 (1, 0, 0): (0.5773502691896258+0j)}

In [5]:
utils_phases.dict_to_hist(res)[:, 1]

array([0.3333333333333334, 0.3333333333333334, 0.3333333333333334],
      dtype=object)

In [6]:
utils_phases.dict_to_quantum_system(res)

([(1, 0, 0), (0, 1, 0), (0, 0, 1)],
 [0.5773502691896258, 0.5773502691896258, 0.5773502691896258],
 [0.0, 0.0, 0.0])

In [7]:
thetas = utils_phases.random_phases(3)
thetas

array([3.30034177, 4.01299907, 3.00624955])

In [8]:
quantum_system = [(0,0,1),
                  (0,1,0),
                  (1,0,0)]
amplitudes = [1/np.sqrt(3)] * 3
phases = thetas

operations = utils_phases.U_XX(0, 3)
res = utils_phases.system_evolution(quantum_system, operations, amplitudes, phases)

In [9]:
res

{(0, 0, 0): (-0.4718701184816063-0.18195332005063564j),
 (0, 0, 1): (-0.2850452753761178-0.04563468329118226j),
 (0, 1, 0): (-0.10020033698565523+0.25985535670445625j),
 (0, 1, 1): (-0.2850452753761178-0.04563468329118226j),
 (1, 0, 0): (0.10020033698565523-0.25985535670445625j),
 (1, 0, 1): (-0.2850452753761178-0.04563468329118226j),
 (1, 1, 0): (0.4718701184816063+0.18195332005063564j),
 (1, 1, 1): (-0.2850452753761178-0.04563468329118226j)}

In [10]:
hist = utils_phases.dict_to_hist(res)
hist

array([[(0, 1, 1), 0.08333333333333333],
       [(1, 1, 0), 0.2557684193932943],
       [(1, 1, 1), 0.08333333333333333],
       [(1, 0, 0), 0.07756491394003905],
       [(0, 0, 1), 0.08333333333333333],
       [(1, 0, 1), 0.08333333333333333],
       [(0, 0, 0), 0.2557684193932943],
       [(0, 1, 0), 0.07756491394003905]], dtype=object)

In [11]:
hist[:, 1].sum()

1.0

In [12]:
sampled = utils_phases.sample_from_hist(hist, 10)
sampled

array([[1., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [16]:
quantum_system = [(0,0,1),
                  (0,1,0),
                  (1,0,0)]
amplitudes = [1 / np.sqrt(3)] * 3
phases = thetas

num_units = 3
num_samples = 10

phases_dataset = dict()

for j in range(num_units - 1):
    operations = utils_phases.U_XX(j, num_units)
    res = utils_phases.system_evolution(quantum_system, operations, amplitudes, phases)  # Resulting states and coefficients.
    hist = utils_phases.dict_to_hist(res)  # States and corresponding probabilities.
    phases_dataset[operations] = utils_phases.sample_from_hist(hist, num_samples)
    
for j in range(num_units - 1):
    operations = utils_phases.U_XY(j, num_units)
    res = utils_phases.system_evolution(quantum_system, operations, amplitudes, phases)  # Resulting states and coefficients.
    hist = utils_phases.dict_to_hist(res)  # States and corresponding probabilities.
    phases_dataset[operations] = utils_phases.sample_from_hist(hist, num_samples)
    
phases_dataset.keys()

dict_keys(['HHI', 'IHH', 'HKI', 'IHK'])